# Generated by Django 4.1 on 2022-08-21 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=55)),
                ('activity_image_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ClimbType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=3, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='HikeSkillLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SummitUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(max_length=50)),
                ('profile_image', models.ImageField(null=True, upload_to='profileimages')),
                ('staff', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('distance', models.DecimalField(decimal_places=4, max_digits=10)),
                ('location', models.CharField(max_length=200)),
                ('estimated_length', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('attractions', models.CharField(max_length=100)),
                ('completed', models.BooleanField(default=False)),
                ('bucket_list', models.BooleanField(default=False)),
                ('hike_image_url', models.URLField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hikes', to='summitapi.activity')),
                ('hike_skill_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hikes', to='summitapi.hikeskilllevel')),
            ],
        ),
        migrations.CreateModel(
            name='Climb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=250)),
                ('completed', models.BooleanField(default=False)),
                ('bucket_list', models.BooleanField(default=False)),
                ('climb_image_url', models.URLField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='climbs', to='summitapi.activity')),
                ('climb_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='climbs', to='summitapi.climbtype')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='climbs', to='summitapi.grade')),
            ],
        ),
    ]
