# Generated by Django 4.1 on 2022-09-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summitapi', '0003_climb_user_hike_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='summituser',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='summituser',
            name='phone_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
