# Generated by Django 4.1 on 2022-09-28 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('summitapi', '0004_summituser_address_summituser_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attraction_type', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='hike',
            name='attractions',
        ),
        migrations.AddField(
            model_name='hike',
            name='attraction_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hikes', to='summitapi.attraction'),
        ),
    ]
