# Generated by Django 4.1 on 2022-09-28 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('summitapi', '0005_attraction_remove_hike_attractions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClimbTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('climb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='climb_tags', to='summitapi.climb')),
            ],
        ),
        migrations.CreateModel(
            name='HikeTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='hike',
            name='attraction_type',
        ),
        migrations.DeleteModel(
            name='Attraction',
        ),
        migrations.AddField(
            model_name='hiketag',
            name='hike',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hike_tags', to='summitapi.hike'),
        ),
        migrations.AddField(
            model_name='hiketag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hike_tags', to='summitapi.tag'),
        ),
        migrations.AddField(
            model_name='climbtag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='climb_tags', to='summitapi.tag'),
        ),
        migrations.AddField(
            model_name='climb',
            name='tag',
            field=models.ManyToManyField(related_name='climbs', through='summitapi.ClimbTag', to='summitapi.tag'),
        ),
        migrations.AddField(
            model_name='hike',
            name='tags',
            field=models.ManyToManyField(related_name='hikes', through='summitapi.HikeTag', to='summitapi.tag'),
        ),
    ]
