# Generated by Django 4.1 on 2022-09-30 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('summitapi', '0007_remove_hike_user_demote_deactivate'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyHike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hikes', models.ManyToManyField(related_name='hikes', to='summitapi.hike')),
                ('summit_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_hikes', to='summitapi.summituser')),
            ],
        ),
        migrations.CreateModel(
            name='MyClimb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('climbs', models.ManyToManyField(related_name='climbs', to='summitapi.climb')),
                ('summit_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_climbs', to='summitapi.summituser')),
            ],
        ),
        migrations.CreateModel(
            name='ListHike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_hikes', to='summitapi.hike')),
                ('my_hike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_hikes', to='summitapi.myhike')),
            ],
        ),
        migrations.CreateModel(
            name='ListClimb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('climb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_climbs', to='summitapi.climb')),
                ('my_climb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_climbs', to='summitapi.myclimb')),
            ],
        ),
    ]
