# Generated by Django 4.1 on 2022-09-30 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summitapi', '0008_myhike_myclimb_listhike_listclimb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='climb',
            old_name='tag',
            new_name='tags',
        ),
        migrations.RemoveField(
            model_name='climb',
            name='user',
        ),
        migrations.AddField(
            model_name='climbtype',
            name='climb_type_image',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_image_url',
            field=models.URLField(null=True),
        ),
    ]
