# Generated by Django 4.1 on 2022-10-12 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summitapi', '0010_remove_climb_bucket_list_remove_climb_completed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='climb',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='hike',
            name='activity',
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
