# Generated by Django 4.1 on 2022-10-25 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summitapi', '0011_remove_climb_activity_remove_hike_activity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myclimb',
            name='bucket_list',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myclimb',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myhike',
            name='bucket_list',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myhike',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
