# Generated by Django 4.1 on 2022-10-25 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summitapi', '0012_myclimb_bucket_list_myclimb_completed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myclimb',
            name='bucket_list',
        ),
        migrations.RemoveField(
            model_name='myclimb',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='myhike',
            name='bucket_list',
        ),
        migrations.RemoveField(
            model_name='myhike',
            name='completed',
        ),
    ]
